controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

reservation:
    resource: '../src/Controller/ReservationController.php'
    type: annotation